name: Build and Deploy

on:
  push:
    branches: [ main ]  # Use "master" instead of "main" if that's your default branch
  pull_request:
    branches: [ main ]  # Use "master" instead of "main" if that's your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Build Site
        run: bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
